- title:      CO₂-Database
  description:  We publish collected processed food items data over the HESTIA database.
  fa-icon:      fa-object-group
  link:

- title:      Github
  description:  We have put the poster source into a public github repository for public use, collaboration and external review.
  fa-icon:      fa-code
  link:

- title:      Poster Campaign
  description:  We crowdfund support to place the poster as an appendix in several newspapers. We think millions of households should have this beautiful piece of art on their fridge.
  fa-icon:      fa-paper-plane-o
  link:
