# - title:      CO₂-Database
#   description:  We publish collected processed food items data over the HESTIA database.
#   fa-icon:      fa-object-group
#   link: http://edb.eaternity.org


# - title:      Poster Campaign
#   description:  We crowdfund support to place the poster as an appendix in several newspapers. We think millions of households should have this beautiful piece of art on their fridge.
#   fa-icon:      fa-paper-plane-o
#   link: http://campact.de

en:
  - title: Github
    description:  We have put the poster source into a public github repository for public use, collaboration and external review.
    fa-icon:      fa-code
    link: https://github.com/AYCE-earth/public/releases/latest

  - title: Interactive Web Version
    description: Tagesspiegel Berlin made the CO₂ Poster interactive for the web. 
    fa-icon:      fa-rocket
    link: https://interaktiv.tagesspiegel.de/lab/wie-klimaschaedlich-sind-beliebte-lebensmittel/

  - title: CodeCheck App
    description: Get the Barcode Scanner and check out your groceries CO₂ foodprint.
    fa-icon:      fa-barcode
    link: https://codecheck-app.com/rating/climatescore/

  - title: Mobile Poster Version
    description: Watson made the CO₂ Poster mobile. To view at your smartphone. 
    fa-icon:      fa-mobile-alt
    link: https://www.watson.ch/wissen/daten/165885444-diese-grafik-zeigt-wie-klimafreundlich-deine-lebensmittel-sind

de:
  - title: Github
    description:  Wir haben den Quellcode des Posters in ein öffentliches Github-Repository für die öffentliche Nutzung, Zusammenarbeit und externe Überprüfung gestellt.
    fa-icon:      fa-code
    link: https://github.com/AYCE-earth/public/releases/latest

  - title: Interaktive Web Version
    description: Der Tagesspiegel Berlin hat das CO₂-Plakat interaktiv für das Web aufbereitet.
    fa-icon:      fa-rocket
    link: https://interaktiv.tagesspiegel.de/lab/wie-klimaschaedlich-sind-beliebte-lebensmittel/

  - title: CodeCheck App
    description: Holen dir den Barcode-Scanner und checke den CO₂ Fussabruck deiner Einkäufe.
    fa-icon:      fa-barcode
    link: https://codecheck-app.com/de/bewertung/klimascore/

  - title: Mobile Poster Version
    description: Watson hat das CO₂-Poster mobil gemacht. Zum Anschauen auf deinem Smartphone. 
    fa-icon:      fa-mobile-alt
    link: https://www.watson.ch/wissen/daten/165885444-diese-grafik-zeigt-wie-klimafreundlich-deine-lebensmittel-sind    